[theme]
base = "light"
primaryColor = "#00205B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FB"
textColor = "#0B1220"
font = "sans serif"
borderColor = "#E4E7EC"

[theme.sidebar]
backgroundColor = "#F8F9FB"

[client]
toolbarMode = "minimal"
showErrorDetails = false
