[theme]
base = "light"
primaryColor = "#147D78"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"

textColor = "#243447"
font = "sans serif"

borderColor = "#D8E0E8"




[theme.sidebar]
backgroundColor = "#F2F5F8"